<script type="text/javascript">
var ruch_is_active=<?php echo $block->isActive(); ?>;
var ruch_is_test=<?php echo $block->isTest(); ?>;
var ruch_show_delivery_filter=<?php echo $block->showDeliveryFilter(); ?>;
var ruch_show_point_type_filter=<?php echo $block->showPointTypeFilter(); ?>;
var ruch_delivery_filter_value=<?php echo $block->getDeliveryFilterValue(); ?>;
var ruch_point_type_filter_value='<?php echo $block->getPointTypeFilterValue(); ?>';
var ruch_widget_url='https://ruch-osm.sysadvisors.pl/widget.js';
</script>
